services:
  actions-runner:
    # Builds the image using the Dockerfile in the current directory.
    build: .
    # Specifies the container name.
    container_name: my-actions-runner
    # Passes GitHub repository information and token as environment variables.
    # GH_TOKEN must be entered directly.
    env_file:
      - .env
    # Restarts the container automatically even if the host reboots.
    restart: always
